#!/usr/bin/env node
/**
 * @fileoverview Extract ABI from Foundry build output for frontend use
 * @description Generates:
 *   1. deployments/abi/PachaChainOrigin.json  - Full ABI array
 *   2. deployments/addresses.json             - Deployed contract addresses by chainId
 *
 * Usage: node scripts/extract-abi.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// ============================================================
//  Input: Foundry build artifacts
// ============================================================

const FOUNDRY_OUT = join(
  ROOT,
  "out",
  "PachaChainOrigin.sol",
  "PachaChainOrigin.json"
);

if (!existsSync(FOUNDRY_OUT)) {
  console.error("❌ Foundry output not found. Run 'forge build' first.");
  process.exit(1);
}

const fullArtifact = JSON.parse(readFileSync(FOUNDRY_OUT, "utf-8"));
const abi = fullArtifact.abi;

// ============================================================
//  Output directory
// ============================================================

const DEPLOY_DIR = join(ROOT, "deployments", "abi");
mkdirSync(DEPLOY_DIR, { recursive: true });

// ============================================================
//  1. Export full ABI
// ============================================================

const abiPath = join(DEPLOY_DIR, "PachaChainOrigin.json");
writeFileSync(abiPath, JSON.stringify(abi, null, 2), "utf-8");
console.log(`✅ ABI exported: ${abiPath} (${abi.length} entries)`);

// ============================================================
//  2. Export TypeScript-friendly ABI (for wagmi/viem)
// ============================================================

const tsContent = `// Auto-generated by scripts/extract-abi.mjs
// Do not edit manually - run: node scripts/extract-abi.mjs

export const PACHA_CHAIN_ORIGIN_ABI = ${JSON.stringify(abi, null, 2)} as const;

export type PachaChainOriginAbi = typeof PACHA_CHAIN_ORIGIN_ABI;
`;

const tsPath = join(DEPLOY_DIR, "PachaChainOrigin.ts");
writeFileSync(tsPath, tsContent, "utf-8");
console.log(`✅ TypeScript ABI: ${tsPath}`);

// ============================================================
//  3. Create/update addresses file
// ============================================================

const addressesPath = join(ROOT, "deployments", "addresses.json");
let addresses = {};

if (existsSync(addressesPath)) {
  addresses = JSON.parse(readFileSync(addressesPath, "utf-8"));
}

// Add defaults if not present
if (!addresses["31337"]) {
  addresses["31337"] = {
    name: "Anvil (Local)",
    contract: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    deployer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    blockNumber: 1,
    note: "Local development - resets on Anvil restart",
  };
}
if (!addresses["80002"]) {
  addresses["80002"] = {
    name: "Polygon Amoy Testnet",
    contract: "",
    deployer: "",
    blockNumber: 0,
    note: "Pending deployment",
  };
}

writeFileSync(addressesPath, JSON.stringify(addresses, null, 2), "utf-8");
console.log(`✅ Addresses: ${addressesPath}`);

// ============================================================
//  Summary
// ============================================================

const functions = abi.filter((e) => e.type === "function");
const events = abi.filter((e) => e.type === "event");
const errors = abi.filter((e) => e.type === "error");

console.log("\n📋 ABI Summary:");
console.log(`   Functions: ${functions.length}`);
console.log(`   Events:    ${events.length}`);
console.log(`   Errors:    ${errors.length}`);
console.log(`   Total:     ${abi.length} entries`);

console.log("\n📝 Functions:");
functions.forEach((f) => {
  const inputs = f.inputs.map((i) => `${i.type} ${i.name}`).join(", ");
  const mutability = f.stateMutability || "";
  console.log(`   ${f.name}(${inputs}) ${mutability}`);
});
